import { Geist, Geist_Mono, Caveat } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${caveat.variable} antialiased`}
      >
        <SmoothScroll>
          {children}
          {/* GetYourGuide Script */}

          <Script
            src="https://widget.getyourguide.com/dist/pa.umd.production.min.js"
            strategy="afterInteractive"
            data-gyg-partner-id="XDZ8IZE"
          />
        </SmoothScroll>
        <Toaster />
      </body>
    </html>
  );
}
